### PR TITLE
Rework `measure!` macro to allow `&mut self` in expr being measured

### PR DESCRIPTION
**Pull request by SimonImbrogno**
Allow `measure!` to take an expression means we can create references to the metric container _as needed_ in the expansion. Therefore, it is no longer needed to store the reference across the scope of the expression being tested, so the expression is free to create and use `&mut self` as needed.

### CODE REVIEW

**Comment by magnet** [comment]
I've tested a larger project and it built fine :) thanks for the PR!  I can merge it as is but ideally could you add a snippet in the demo that uses an &mut ref as a test so we make sure it doesn't break?  In any case I will try to cut a release with this soon!

**Comment by magnet** [comment]
The closure is necessary to support early returns.

**Comment by SimonImbrogno** [comment]
Ahhh... Ok. 

Then the issue becomes that the closure takes ownership of `self` so the references no longer pass the borrow check... hmm. I think we can get around that though, if the reference to the metrics object is coerced into a raw pointer. Ill have to do some experimentation, but I think this may still work.

**Comment by magnet** [comment]
Isn't that unsafe block UB? Afaik if you're aliasing self as &mut then you cannot have another borrow to the same location, even if you can prove the &mut borrow doesn't touch &self.metrics.

**Comment by SimonImbrogno** [comment]
> Isn't that unsafe block UB? Afaik if you're aliasing self as &mut then you cannot have another borrow to the same location, even if you can prove the &mut borrow doesn't touch &self.metrics.

Hmm. I didn't think it was but now I'm second guessing. The documentation is not 100% clear on this... I was under the impression that having two `&mut` (by coercing a pointer back into a `&`/`&mut`), or by modifying a the data underneath a `&mut` indirectly _was definitely UB_ as this breaks optimizer assumptions about references. But in this case we don't use the `*mut` to touch the data it points to until _after_ the reference that created it is dropped. 

It's my understanding that the UB arises because the optimizer assumes that data pointed to by a `&mut` will only be modified (or viewed) through that specific borrow, so it is free to rearrange instructions accessing that memory over the lifetime of the borrow. However, once the borrow goes out of scope and is dropped, I would imagine the guarantee of unique access is dropped along with it. 

I may be mistaken but that was my impression. 🤔

**Comment by magnet** [comment]
Yeah I'm not sure either, maybe the stack borrow checker in miri could find out?

Aside from the UB, the metric could now be moved in the user code (`$e`). It wouldn't happen from methods where the metric is a part of `self`, but something like (pseudo-code):

```rust
fn test_unknown() {
    let metrics = TestMetrics::default();
    let error_count = metrics.error_count;
    measure!(&error_count, {
        println!("wtf?!");
        std::mem::drop(error_count);
        <Result<(), ()>>::Err(())
    });
}
```

This is not crashing on my laptop, but I think this isn't memory safe:  `on_result` will be called on the original address of `&error_count` -- but it has moved since.  That would be difficult to do from the procedural macro because `&self` is borrowed there, but it would make the `measure` macro unsafe.

**Comment by bonsairobo** [comment]
What needs to happen to resolve this issue? I'd like to use this crate, but I'm blocked on being able to use `&mut self` in measured methods. Specifically, I get this error:

```
error[E0505]: cannot move out of `self` because it is borrowed
  --> src/generate.rs:21:1
   |
21 | #[metered(registry = GeneratorMetrics)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | |
   | borrow of `self.metrics.observe_slot.throughput` occurs here
   | move out of `self` occurs here
   | borrow later used here
...
74 |         let pattern = self.sample_pattern(patterns, slot);
   |                       ---- move occurs due to use in closure
   |
```

**Comment by SimonImbrogno** [comment]
> What needs to happen to resolve this issue? I'd like to use this crate, but I'm blocked on being able to use `&mut self` in measured methods.

Yeah I was in your situation...  It's probably more than just a small change. I had thought that it would just be a matter of cleaning up how the contained code block was wrapped but it's not quite that simple. 

Handling early returns, `&mut self` use in the measured function, and avoiding UB in the generated code would probably require a bit of a rework of how the macro works internally. 

Also the function style `measure!` macro seems to work slightly differently than the attribute  `#[metered(registry = GeneratorMetrics)]` macro... (I don't recall the specifics but I think one of them _doesn't_ correctly handle multiple returns?)

**Comment by magnet** [comment]
As mentioned earlier I believe this is unsound, and believe it is required to compose the metric in an outer struct to achieve this safely.  Closing this until we revisit it safely.

**Pull request closed without merging**
